[build]
  command = "next build"
  environment = { NODE_VERSION = "18.18.0" }
  publish = '.next'

[context.production]
  environment = { NODE_VERSION = "18.18.0" }

[[plugins]]
  package = "@netlify/plugin-nextjs"