[build]
  command = "next build"
  environment = { NODE_VERSION = "22.12.0" }
  publish = '.next'

[context.production]
  environment = { NODE_VERSION = "22.12.0" }

[[plugins]]
  package="@opennextjs/netlify"